[pytest]
testpaths = tests
pythonpath = .
addopts =
    --tb=short
    --cov=src
    --cov-report=term-missing
    --cov-fail-under=80
    --cov-config=pytest.ini

[coverage:run]
omit =
    src/fastapi_general.py
    src/retrieved_results.py
    src/evaluate.py